### PR TITLE
Release 0.16.0

### PR DESCRIPTION
**Pull request by hagenw**
image

### CODE REVIEW

**Comment by hagenw** [comment]
I thought it's time for the big 1.0.0 release, do you agree?

**Comment by frankenjoe** [comment]
> I thought it's time for the big 1.0.0 release, do you agree?

Yes, good idea. We have a couple of issues marked as bug. If we go for 1.0.0 we should probably check whether those bugs still exist and if yes try to solve them first.

**Comment by hagenw** [comment]
We have the following open bugs at the moment:

* https://github.com/audeering/audformat/issues/256: this shouldn't be urgent
* https://github.com/audeering/audformat/issues/317: this will be not that easy to solve
* https://github.com/audeering/audformat/issues/324: this is related to the previous issue. In summary we need to make sure that `CategoricalDtype` is preserved by methods like `get()`
* https://github.com/audeering/audformat/issues/328: this should not affect the user, only developers

It might be that we want to fix #317 and #324 first before making the release. The downside is that we need a release to continue working on the attachment feature in `audb`. We could change the version of this release to `0.16.0`, but I'm also fine with doing `1.0.0` and release the somehow breaking change we are doing when solving #317 and #324 as a bug fix.

**Comment by frankenjoe** [comment]
I created a fix for #256 

As you already said, #317 and #324 are not that straightforward to solve. Yet, I think we should solve them before we release 1.0.0. So I would go for 0.16.0 for the moment.

**Comment by hagenw** [comment]
I changed the version to `0.16.0` and mention your fix from #256

**Comment by hagenw** [comment]
#256 is merged and this should now be ready for review.

**Pull request merged**
