### PR TITLE
WIP: Remove oyaml dependency

### PR DESCRIPTION
**Pull request by hagenw**
Seems by just replacing `oyaml` with `pyyaml` we get a lot of failing tests.

### CODE REVIEW

**Comment by hagenw** [comment]
`pyyaml` is always returning something like 

```
     scheme_id:                                                                                                                                                                                
    -  dtype: str                                                                                                                                                                              
    -  labels: [a, b]                                                                                                                                                                          
    +  !!python/object/apply:collections.OrderedDict 
```

so I guess we have to update our string representations?

**Comment by frankenjoe** [comment]
> so I guess we have to update our string representations?

I think what's happening is that by `pyyaml` does not properly serialize `collections.OrderedDict` but only `dict`. Whereas `oyaml`, which internally builds on `collections.OrderedDict` for ordered dictionaries naturally can cope with it. So I guess, if we find that `pyyaml` does preserve ordering, we have to replace  `collections.OrderedDict` with `dict`.

**Comment by frankenjoe** [comment]
But then we have to see if deriving from `dict` will actually work as expected, there seems to be cases where it is ok, but not always, see https://treyhunner.com/2019/04/why-you-shouldnt-inherit-from-list-and-dict-in-python/

**Comment by hagenw** [comment]
Why do we have to derive from `dict` and cannot simply use `dict`?

**Comment by frankenjoe** [comment]
> Why do we have to derive from `dict` and cannot simply use `dict`?

Because of the `HeaderDict` class: https://github.com/audeering/audformat/blob/9613efcccf0c45fb78432c237d784067ccc03b17/audformat/core/common.py#L16

**Comment by hagenw** [comment]
I see one way around would be to convert to `dict` before dumping and after reading from the YAML file, but I'm not sure if this is worse the effort.
Maybe as long as `oyaml` works with the newest versions of `pyyaml` we simply stay with the current solution?

**Comment by frankenjoe** [comment]
I did  a quick check with the latest version of `pyyaml` (6.0) and turns out it anyway does not preserve the order of dictionaries:

```python
>>> import yaml
>>> d = {'this': 0, 'is': 1, 'an': 2, 'awesome': 3, 'dict': 4} 
>>> print(yaml.dump(d))
an: 2
awesome: 3
dict: 4
is: 1
this: 0
```

So we anyway have to stick to `oyaml`.

**Comment by hagenw** [comment]
Mh, ok. I guess they support the order, but they seem to order it themselves before storing.

I will simply close this and we hope `oyaml` will work the next few years, otherwise we need to take it over ;)

**Pull request closed without merging**
