### PR TITLE
Release 0.14.2

### PR DESCRIPTION
**Pull request by frankenjoe**
image

### CODE REVIEW

**Comment by hagenw** [comment]
You forgot that we also had https://github.com/audeering/audformat/pull/164. And I guess there is also work to be done in https://github.com/audeering/audformat/pull/162, or is everything integrated now that @Bahaabrougui needs for `audbenchmark`?

**Comment by frankenjoe** [comment]
Oh yes we should add #164 of course. But don't you think it's important we get a version out that supports latest pandas right away?

**Comment by hagenw** [comment]
We are missing support for `pandas` 1.4.0 now since some time, so I think we can also wait a few more days.

**Comment by frankenjoe** [comment]
Ok, I'll put WIP.

**Comment by Bahaabrougui** [comment]
> You forgot that we also had #164. And I guess there is also work to be done in #162, or is everything integrated now that @Bahaabrougui needs for `audbenchmark`?

#162 is no longer WIP and can be merged too

**Comment by frankenjoe** [comment]
@Bahaabrougui any other function you wanted to integrate or are we good to go?

**Comment by Bahaabrougui** [comment]
> @Bahaabrougui any other function you wanted to integrate or are we good to go?

Nope, all good

**Pull request merged**
