### PR TITLE
Release 0.12.0

### PR DESCRIPTION
**Pull request by hagenw**
I finished my checks regarding our latest changes and haven't found anything I would like to change before a new release.

Do you want to tackle https://github.com/audeering/audformat/issues/111 first, or should we proceed here?

### CODE REVIEW

**Comment by frankenjoe** [comment]
> Do you want to tackle #111 first, or should we proceed here?

Would be nice to tackle #111. Implementing shouldn't be hard, it's rather a question which design we choose.

**Comment by hagenw** [comment]
OK, fine with me.

**Comment by hagenw** [comment]
I updated the changelog by our latest additions.

I guess we are now fine for the release?

**Comment by frankenjoe** [comment]
> I guess we are now fine for the release?

Yes, please go ahead.

**Pull request merged**
