### PR TITLE
Allow pandas>=1.4.x

### LINKED ISSUE #169: Figure out why `pd.read_csv()` fails with `pandas >= 1.4.0`.
See https://github.com/audeering/audformat/pull/142#issuecomment-1020175759 and https://github.com/audeering/audformat/pull/168

### PR DESCRIPTION
**Pull request by hagenw**
Closes #169

With #171 we can add support for pandas >= 1.4.0.

### CODE REVIEW

**Comment by hagenw** [comment]
Seems like our code does still not work with `pandas>=1.4.0` (it installed 1.4.2 in the CI job). So maybe we should open an issue here pointing out, that we need to fix this maybe ourselves?

**Comment by frankenjoe** [comment]
Do you know where we initially discussed why it is failing. I think it was related to the `DataFrame.to_csv()` function.

**Comment by hagenw** [comment]
> Do you know where we initially discussed why it is failing. I think it was related to the `DataFrame.to_csv()` function.

https://github.com/audeering/audformat/pull/142#issuecomment-1020186163

**Comment by frankenjoe** [comment]
Thanks, so it's actually the `read_csv()` function causing the issues. So yes we probably have to take a closer look why it happens, maybe they changed a default argument or something like this.

**Comment by hagenw** [comment]
> Thanks, so it's actually the `read_csv()` function causing the issues. So yes we probably have to take a closer look why it happens, maybe they changed a default argument or something like this.

Can you open an issue so we don't forget it.

**Comment by frankenjoe** [comment]
https://github.com/audeering/audformat/issues/169

**Comment by frankenjoe** [comment]
A fix is provided in #170

**Comment by frankenjoe** [comment]
@hagenw tests are passing! Please assign to me and I will merge.

**Comment by hagenw** [comment]
Great

**Pull request merged**
