### PR TITLE
WIP: Combine database objects

### PR DESCRIPTION
**Pull request by frankenjoe**
Implements `Database.__add__()` that creates a new object from two databases.

### Example:

Create a simple database with one table:

```python
db = audformat.testing.create_db(minimal=True)
db.description = 'Some test database.'
db.schemes['str'] = audformat.Scheme()
db.expires = datetime.date(2023, 1, 1)
db.meta = {'foo': 'bar'}
audformat.testing.add_table(db, 'table', audformat.define.IndexType.FILEWISE)
db
```
```
name: unittest
description: Some test database.
source: internal
usage: unrestricted
expires: 2023-01-01
languages: [deu, eng]
schemes:
  str: {dtype: str}
tables:
  table:
    type: filewise
    columns:
      str: {scheme_id: str}
foo: bar
```

Now combine with `emodb` database:

```python
emodb = audformat.Database.load(...)
db + emodb
```
```
name: unittest+emodb
description: Some test database. Berlin Database of Emotional Speech. A German database of emotional
  utterances spoken by actors recorded as a part of the DFG funded research project
  SE462/3-1 in 1997 and 1999. Recordings took place in the anechoic chamber of the
  Technical University Berlin, department of Technical Acoustics. It contains about
  500 utterances from ten different actors expressing basic six emotions and neutral.
source: internal,http://emodb.bilderbar.info/download/download.zip
usage: unrestricted
expires: 2023-01-01
languages: [eng, deu]
media:
  microphone: {type: other, format: wav, channels: 1, sampling_rate: 16000}
raters:
  gold: {type: human}
schemes:
  confidence: {description: Confidence of emotion ratings., dtype: float, minimum: 0,
    maximum: 1}
  duration: {dtype: time}
  emotion:
    description: Six basic emotions and neutral.
    dtype: str
    labels: [anger, boredom, disgust, fear, happiness, sadness, neutral]
  speaker:
    description: The actors could produce each sentence as often as they liked and
      were asked to remember a real situation from their past when they had felt this
      emotion.
    dtype: int
    labels:
      3: {gender: male, age: 31, language: deu}
      8: {gender: female, age: 34, language: deu}
      9: {gender: male, age: 21, language: deu}
      10: {gender: female, age: 32, language: deu}
      11: {gender: male, age: 26, language: deu}
      12: {gender: female, age: 30, language: deu}
      13: {gender: male, age: 32, language: deu}
      14: {gender: female, age: 35, language: deu}
      15: {gender: male, age: 25, language: deu}
      16: {gender: female, age: 31, language: deu}
  str: {dtype: str}
  transcription:
    description: Sentence produced by actor.
    dtype: str
    labels: {a01: Der Lappen liegt auf dem Eisschrank., a02: Das will sie am Mittwoch
        abgeben., a04: Heute abend könnte ich es ihm sagen., a05: Das schwarze Stück
        Papier befindet sich da oben neben dem Holzstück., a07: In sieben Stunden
        wird es soweit sein., b01: 'Was sind denn das für Tüten, die da unter dem
        Tisch stehen.', b02: Sie haben es gerade hochgetragen und jetzt gehen sie
        wieder runter., b03: An den Wochenenden bin ich jetzt immer nach Hause gefahren
        und habe Agnes besucht., b09: Ich will das eben wegbringen und dann mit Karl
        was trinken gehen., b10: 'Die wird auf dem Platz sein, wo wir sie immer hinlegen.'}
tables:
  emotion:
    type: filewise
    columns:
      emotion: {scheme_id: emotion, rater_id: gold}
      emotion.confidence: {scheme_id: confidence, rater_id: gold}
  files:
    type: filewise
    columns:
      duration: {scheme_id: duration}
      speaker: {scheme_id: speaker}
      transcription: {scheme_id: transcription}
  table:
    type: filewise
    columns:
      str: {scheme_id: str}
audb:
  root: /media/jwagner/Data/audb2/data-public-local/emodb/5030d22e-33a9-2386-1e03-693d20589cce/1.1.0
  version: 1.1.0
  flavor: {only_metadata: false, bit_depth: null, channels: null, format: null, mixdown: false,
    sampling_rate: null, tables: null, exclude: null, include: null}
foo: bar
pdf: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.130.8506&rep=rep1&type=pdf
```

### Discussion

Turns out it's not so obvious what we should with some of the header fields if they do not match. Here's a list of fields that are up to discussion:

| field | result |
| - | - |
| name | 'name1+name2' |
| description | 'description1 description2' |
| source | 'source1,source2' |
| usage | error |
| expires | min(expires1, expires2) |
| languages | set([languages1, languages2]) |
| meta | meta1.update(meta2) |

For complex fields like `schemes` or `raters` an error is raised if contain different objects with the same ID.

### CODE REVIEW

**Comment by frankenjoe** [comment]
@hagenw I didn't add tests yet, since I am sure you will have some comments :) So please feel free to play around with this first attempt to implement that function.

**Comment by hagenw** [comment]
```python
import datetime

import audformat
import audformat.testing


db1 = audformat.testing.create_db(minimal=True)
db1.description = 'Some test database.'
db1.schemes['str'] = audformat.Scheme()
db1.expires = datetime.date(2023, 1, 1)
db1.meta = {'foo': 'bar'}
audformat.testing.add_table(db1, 'table', audformat.define.IndexType.FILEWISE)

db2 = audformat.testing.create_db(minimal=True)
db2.description = 'Some test database.'
db2.schemes['str'] = audformat.Scheme()
db2.expires = datetime.date(2023, 1, 1)
db2.meta = {'foo': 'bar'}
audformat.testing.add_table(db1, 'table', audformat.define.IndexType.FILEWISE)
db2['table'].df.index = audformat.filewise_index(
    ['audio/006.wav', 'audio/007.wav', 'audio/008.wav', 'audio/009.wav', 'audio/010.wav']
)
```

Now we have:

```python
>>> db1['table'].df
                      str
file                     
audio/001.wav  qpr1PAOeDg
audio/002.wav  LlqOHnelnr
audio/003.wav  UsckGewlsb
audio/004.wav  FlgNqzonEO
audio/005.wav  H460HrhTrM

>>> db2['table'].df
                      str
file                     
audio/006.wav  9cBIZyDVTH
audio/007.wav  F2K4YzIth7
audio/008.wav  WMB1gycWhL
audio/009.wav  CihTY03Ls3
audio/010.wav  1WWsCbAhqB

>>> db = db1 + db2
>>> db['table'].df
                      str
file                     
audio/001.wav  qpr1PAOeDg
audio/002.wav  LlqOHnelnr
audio/003.wav  UsckGewlsb
audio/004.wav  FlgNqzonEO
audio/005.wav  H460HrhTrM
audio/006.wav  9cBIZyDVTH
audio/007.wav  F2K4YzIth7
audio/008.wav  WMB1gycWhL
audio/009.wav  CihTY03Ls3
audio/010.wav  1WWsCbAhqB

>>> db = db2 + db1
>>> db['table'].df
                      str
file                     
audio/001.wav  qpr1PAOeDg
audio/002.wav  LlqOHnelnr
audio/003.wav  UsckGewlsb
audio/004.wav  FlgNqzonEO
audio/005.wav  H460HrhTrM
audio/006.wav  9cBIZyDVTH
audio/007.wav  F2K4YzIth7
audio/008.wav  WMB1gycWhL
audio/009.wav  CihTY03Ls3
audio/010.wav  1WWsCbAhqB
```

I guess the goal that the last command does not return
```
                      str
file                     
audio/006.wav  9cBIZyDVTH
audio/007.wav  F2K4YzIth7
audio/008.wav  WMB1gycWhL
audio/009.wav  CihTY03Ls3
audio/010.wav  1WWsCbAhqB
audio/001.wav  qpr1PAOeDg
audio/002.wav  LlqOHnelnr
audio/003.wav  UsckGewlsb
audio/004.wav  FlgNqzonEO
audio/005.wav  H460HrhTrM
```
is the fact that we want to make sure that `db1 + db2 == db2 + db1`, correct?
At least that would make sense to me.

**Comment by frankenjoe** [comment]
> is the fact that we want to make sure that db1 + db2 == db2 + db1, correct?

at the moment not, because table1 + table2 != table2 + table1, see https://github.com/audeering/audformat/issues/24

**Comment by frankenjoe** [comment]
Though in your example table1 + table2 == table2 + table1 actually holds, but that's not the case in general.

**Comment by hagenw** [comment]
| field | result |
| - | - |
| name | 'name1+name2' |
| description | 'description1 description2' |
| source | 'source1,source2' |
| usage | error |
| expires | min(expires1, expires2) |
| languages | set([languages1, languages2]) |
| meta | meta1.update(meta2) |

Good question, an alternative would be that the first or second database takes over for some of those fields, e.g.

| field | result |
| - | - |
| name | 'name1' |
| description | 'description1' |
| source | 'source1' |
| usage | error |
| expires | min(expires1, expires2) |
| languages | set([languages1, languages2]) |
| meta | meta1.update(meta2) |

On the other hand you might argue that the second database is actual the one that should update the first one, and maybe we should use the values from the second database and not from the first?

Maybe, it's safer we stay with your proposal and incorporate both if the values differ.

**Comment by frankenjoe** [comment]
For `usage` I decided to raise an error and of course we could also do that for other fields, but I don't think we should be too restrictive. Another solution would be to not implement `__add__` but have a function `audformat.combine_db` (or similar) and add options for `name`, etc. which are `None` by default, but if the fields do not match have to be set by the user. On the other hand I like the symmetry with `table1 + table2` and the user can always do:

```python
db = db1 + db2
db.name = 'foo'
```

**Comment by frankenjoe** [comment]
Btw: currently if we have `db1.meta['foo'] = 'foo` and `db2.meta['bar'] = 'bar', `(db1 + db2).meta['foo']` will be `bar`. You think we should rather raise an error if two meta fields with the same key do not match?

**Comment by hagenw** [comment]
We could also do a combination of `__add__` and `combine_db`.

```python
db1 + db2
```
will then raise an error if `name`, `description`, `source`, or `usage` are different and point you to use `combine_db` where you can then specify the new `name`, etc.

We could then also think about supporting something like:

```python
db1 + db2 == db2 + db1
```
which don't have to be the case for `combine_db`.

But then of course we can not do `(db1 + db2).meta['foo'] == 'bar'`. If we not plan to support `db1 + db2 == db2 + db1`, then I think it is fine for some fields that they can be overwritten by the second database.

But in principle, we could also raise an error for all fields where there is no meaningful way to combine them and point to `combine_db()`

**Comment by frankenjoe** [comment]
> But in principle, we could also raise an error for all fields where there is no meaningful way to combine them and point to combine_db()

Ok, we now get an error if `db1.meta['key'] != db2.meta['key']`.

> We could also do a combination of __add__ and combine_db.

We could do that, but at the moment I'm more in favor of only implementing `__add__`. I guess it also depends a bit on the use-case. If we add databases locally to get the combined tables to e.g. train a model, then it is not so important how we combine fields like `name` or `source'. But in case we want to update an existing database with new data and publish it afterwards, then it's of course important. However, in that latter case it is also more likely that fields like `name` and `source` fit anyway.

**Comment by frankenjoe** [comment]
Closing in favor of #55

**Pull request closed without merging**
